// --------------------------------------------------------
// Copyright (c)
//
// contributions by author
//                  author@somewhere.net
// maintained by    maintainer
//                  maintainer@somewhere.net

// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#ifndef PF_RADAR_ADAPTER_CD_PF_RADAR_ADAPTER_IMPL_H
#define PF_RADAR_ADAPTER_CD_PF_RADAR_ADAPTER_IMPL_H

/************************************************************
 pf_radar_adapter_impl class header
 ************************************************************/

#include "pf_radar_adapter_cd/Pkg_pf_radar_adapter_cd.h"

#include "canopen_interfaces/msg/co_data.hpp"
#include "pf_radar_adapter_cd/pf_radar_adapter.h"

namespace ros2Library {
namespace rclcpp {
class NodeOptions;
}
}

namespace pf_radar_adapter_cd {

/************************************************************/
/**
 * This is a skeleton class generated for component pf_radar_adapter
 * Copy it into the source folder as an initial base (or copy parts
 * of it whenever you add modify the component).
 * 
 */
class pf_radar_adapter_impl: public pf_radar_adapter {
public:

  /**
   * 
   * @param options 
   */
  pf_radar_adapter_impl(rclcpp::NodeOptions /*in*/options);

  /**
   * 
   */
  void radar_publisher();

  /**
   * 
   * @param commobj 
   */
  void co_data_handler(
      const canopen_interfaces::msg::COData::SharedPtr /*in*/commobj);

};
/************************************************************/
/* External declarations (package visibility)               */
/************************************************************/

/* Inline functions                                         */

} // of namespace pf_radar_adapter_cd

/************************************************************
 End of pf_radar_adapter_impl class header
 ************************************************************/

#endif
