// --------------------------------------------------------
// Copyright (c)
//
// contributions by author
//                  author@somewhere.net
// maintained by    maintainer
//                  maintainer@somewhere.net

// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#define pf_radar_adapter_cd_pf_radar_adapter_impl_BODY

/************************************************************
 pf_radar_adapter_impl class body
 ************************************************************/

// include associated header file
#include "pf_radar_adapter_cd/pf_radar_adapter_impl.h"

// Derived includes directives
#include "rclcpp/rclcpp.hpp"

namespace pf_radar_adapter_cd {

// static attributes (if any)

/**
 * 
 * @param options 
 */
pf_radar_adapter_impl::pf_radar_adapter_impl(rclcpp::NodeOptions /*in*/options) :
    pf_radar_adapter(options) {
}

/**
 * 
 */
void pf_radar_adapter_impl::radar_publisher() {
}

/**
 * 
 * @param commobj 
 */
void pf_radar_adapter_impl::co_data_handler(
    const canopen_interfaces::msg::COData::SharedPtr /*in*/commobj) {
}

} // of namespace pf_radar_adapter_cd

/************************************************************
 End of pf_radar_adapter_impl class body
 ************************************************************/
