// --------------------------------------------------------
// Copyright (c)
//
// contributions by author
//                  author@somewhere.net
// maintained by    maintainer
//                  maintainer@somewhere.net

// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#ifndef PF_RADAR_ADAPTER_CD_PF_RADAR_ADAPTER_H
#define PF_RADAR_ADAPTER_CD_PF_RADAR_ADAPTER_H

/************************************************************
 pf_radar_adapter class header
 ************************************************************/

#include "pf_radar_adapter_cd/Pkg_pf_radar_adapter_cd.h"

#include "canopen_interfaces/msg/co_data.hpp"
#include "pf_radar_interfaces_sd/msg/radar.hpp"
#include "rclcpp_lifecycle/lifecycle_node.hpp"

// Include from Include stereotype (header)
#include <rclcpp/rclcpp.hpp>

// End of Include stereotype (header)

namespace ros2Library {
namespace rclcpp {
class CallbackGroup;
}
}
namespace ros2Library {
namespace rclcpp {
class NodeOptions;
}
}
namespace ros2Library {
namespace rclcpp {
class Subscription;
}
}

namespace pf_radar_adapter_cd {

/************************************************************/
/**
 * 
 */
class pf_radar_adapter: public rclcpp_lifecycle::LifecycleNode {
public:

  /**
   * 
   */
  rclcpp::CallbackGroup::SharedPtr cbg_publisher_;

  /**
   * 
   */
  rclcpp::CallbackGroup::SharedPtr cbg_reader_;

  /**
   * 
   */
  rclcpp_lifecycle::LifecyclePublisher<pf_radar_interfaces_sd::msg::Radar>::SharedPtr radar_pub_;

  /**
   * 
   */
  rclcpp::Subscription<canopen_interfaces::msg::COData>::SharedPtr _pepperl_proxy_device_1_rpdo_sub_;

  /**
   * 
   * @param options 
   */
  pf_radar_adapter(rclcpp::NodeOptions /*in*/options);

};
/************************************************************/
/* External declarations (package visibility)               */
/************************************************************/

/* Inline functions                                         */

} // of namespace pf_radar_adapter_cd

/************************************************************
 End of pf_radar_adapter class header
 ************************************************************/

#endif
