// --------------------------------------------------------
// Copyright (c)
//
// contributions by author
//                  author@somewhere.net
// maintained by    maintainer
//                  maintainer@somewhere.net

// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#include "pf_radar_adapter_cd/pf_radar_adapter_impl.h"

// declare options
rclcpp::NodeOptions pf_radar_adapter_options;

int main(int argc, char **argv) {
  rclcpp::init(argc, argv);

  auto pf_radar_adapter = std::make_shared
      < pf_radar_adapter_cd::pf_radar_adapter_impl > (pf_radar_adapter_options);

  RCLCPP_INFO(pf_radar_adapter->get_logger(),
      "pf_radar_adapter has been initialized");

  rclcpp::executors::MultiThreadedExecutor executor;

  executor.add_node(pf_radar_adapter->get_node_base_interface());

  executor.spin();
  rclcpp::shutdown();
}

